### ISSUE TITLE
Mixed type chromosome

### ISSUE THREAD

**Issue by SimonG85** [basvanwesting/genetic-algorithm#1]
I'm learning both rust and genetic algos, and I'm watching your library (and I'd like to contribute).
Is it possibile to define a Chromosome with mixed type? I mean, for example, integer and real type together? 
If take a look at Chromosome struct it has two fields, genes and fitness_score.

Genes have to be a vector of generic T of alleles but the type T is the same for all gene.

**Comment by basvanwesting** [comment]
Interesting idea... What type of problem would you like to solve with a mixed type?

**Comment by SimonG85** [comment]
Think about a time series. Your model required a number of n lags of the time series and a renormalizzation of that quantity with some parameters (e.g. a log transformation with a scale parameter and an offset).
In this case your parameters (to be optimised) are an integer and two real and in the new generation n parameter has to be integer.

**Comment by basvanwesting** [comment]
Yes, I see. It's tricky. 

First some history: I tried having a heterogenous type before, but it was quite hard to do (for me). Trait objects weren't allowed, due to the use of generics. Alternative approaches using Any and enum worked, but were not flexible enough in nature to generalize and provide a part of the library. So, after some consideration I settled on using an nested index based Genotype `MultiDiscreteGenotype<usize>` indices of external vectors of arbitrary types, which should then be retrieved in the fitness function. This was a much easier approach for a genotype of type "list of different typed lists".

So in the end, redefining the problem space was easier. This could be an option for you as well: just use the `MultiContinuousGenotype` and round the genes that need to be an integer to integer in the fitness function. The `MultiContinuousGenotype` allows for separate sample ranges for each gene, so scaling the genes appropriately for useful rounding to integer should be efficient enough.

Alternatively, I we really want a mixed type, I think maybe an enum type with an integer and a real would be easiest. But it would still be tricky, because you would need a mutation function which is specific to the position as well. Making it a generic solution is hard. 

Thinking about that, you could define a more specific TimeSeriesGenotype for the specific problem space. Get that to work elegantly and then consider generalization. You think that would be a useful first step?

**Comment by SimonG85** [comment]
Thanks.
Actually I don't know if this can solve my problem and I'm not able to provide a concrete example soon.
I'm working in python but I want to switch on rust. But I'm not able to write code in rust proficiency (for now).
My fitness function uses polars (with its python binding) and I'm exploring the universe of rust library (keeping in mind what I need to solve).

**Comment by basvanwesting** [comment]
In that case, I would use an all real genotype and round the relevant genes to integer in the fitness function. You could possibly explore that in python as well.

If you can provide me the details of your specific problem, I can add an example using `MultiContinuousGenotype` for you in this repo.

**Comment by SimonG85** [comment]
Are you sure that round to integer is a good choice?
If an integer parameter lives in [0, 5] in N it can take only 6 values but the same interval as a subset of R is much more complicated (for example in population generation).
Do you agree with me?

**Comment by basvanwesting** [comment]
If you have a real interval [0, 6) with an uniform probability, then taking the floor of the sample would result in a uniform [0,5] integer distribution. There would be a little bit of calculation overhead for the sampling and rounding, but I expect that to be negligible.

**Comment by SimonG85** [comment]
I see your point. With floor in uniform distribution should work.
What do you need for the example? Maybe something like [(https://en.wikipedia.org/wiki/Test_functions_for_optimization)]
but for mixed integer problems could be useful to test the quality of optimal points.

**Comment by basvanwesting** [comment]
I didn't know about https://en.wikipedia.org/wiki/Test_functions_for_optimization. Very useful indeed.
But I can't seem to find a mixed R/N problem. Could you point me to one that is of interest for you?

**Comment by SimonG85** [comment]
Yes, very useful as test case.
On Matlab doc there are a lot of examples with integer constraint: https://www.mathworks.com/help/optim/ug/intlinprog.html
It could be a good starting point.

**Comment by basvanwesting** [comment]
Setting the evolve parameters is always a little bit of trail-and-error. I added a meta-example for tweaking these:
Run with `cargo run --example meta_evolve_milp --release`

The results seem more stable with the following settings:
```
  .with_population_size(1000)
  .with_max_stale_generations(1000)
  .with_mutate(MutateOnce(0.4))
  .with_crossover(CrossoverSingleGene(true))
  .with_compete(CompeteElite);
```

Results
```
x1: 6.75001, x2: 5 = 59.00009 (fitness score:     9, duration 403.922779ms)
x1: 6.75000, x2: 5 = 59.00003 (fitness score:     3, duration 352.940985ms)
x1: 6.87499, x2: 4 = 58.99992 (fitness score:     7, duration 219.87425ms)
x1: 6.62500, x2: 6 = 59.00003 (fitness score:     3, duration 333.118143ms)
x1: 6.74999, x2: 5 = 58.99992 (fitness score:     7, duration 230.75682ms)
x1: 6.87500, x2: 4 = 59.00000 (fitness score:     0, duration 260.38824ms)
x1: 6.49993, x2: 7 = 58.99942 (fitness score:    57, duration 251.719449ms)
x1: 6.49999, x2: 7 = 58.99994 (fitness score:     6, duration 399.972354ms)
x1: 6.74999, x2: 5 = 58.99991 (fitness score:     9, duration 245.576712ms)
x1: 6.75000, x2: 5 = 59.00003 (fitness score:     3, duration 421.845383ms)
```

**Comment by SimonG85** [comment]
Thanks.
I have a Matlab copy and I can provide the same example and send you some metrics.
I have another question about the fitness function return value but I'll open another issue.

**Comment by basvanwesting** [comment]
I figured that one of the inefficiencies of the current approach was that the random gene mutation was taken as a uniform sample from the complete allowed range. The makes mutation very wild and results in a lot of useless mutations.

So I added the (optional) concept of a neighbouring mutation. It is set on the genotype and restricts the mutation to the provided ranges. This way the mutation behaves more like zooming in on the correct solution, instead of mutating randomly all over the place.

```
    let genotype = MultiContinuousGenotype::builder()
        .with_allele_multi_range(vec![(-100.0..100.0), (0.0..100.0)])
        .with_allele_multi_neighbour_range(vec![(-1.0..1.0), (-1.0..1.0)])
        .build()
        .unwrap();

```

It will probably increase the risk of locking into an local optimum. But the population size (or maybe the nature of the problem) compensates for that in this situation. The results are now more precise and a bit faster:

```
x1: 6.50000, x2: 7 = 58.99999 (fitness score:     1, duration 205.36629ms)
x1: 6.50000, x2: 7 = 58.99998 (fitness score:     2, duration 196.71682ms)
x1: 6.62500, x2: 6 = 59.00001 (fitness score:     0, duration 167.83452ms)
x1: 6.62500, x2: 6 = 58.99999 (fitness score:     0, duration 68.890299ms)
x1: 6.75000, x2: 5 = 59.00000 (fitness score:     0, duration 52.330101ms)
x1: 6.62500, x2: 6 = 59.00002 (fitness score:     2, duration 230.258832ms)
x1: 6.75000, x2: 5 = 58.99999 (fitness score:     0, duration 115.138755ms)
x1: 6.62500, x2: 6 = 59.00000 (fitness score:     0, duration 284.482541ms)
x1: 6.75000, x2: 5 = 59.00001 (fitness score:     0, duration 264.155117ms)
x1: 6.62500, x2: 6 = 58.99998 (fitness score:     1, duration 190.504497ms)
```

**Comment by basvanwesting** [comment]
Interestingly, the hill-climb approach demonstrates the locality issue with neighbouring mutations clearly:
if the initial chromosome hits something near a solution, it converges fast. But if it doesn't it is pretty much lost:

```
invalid solution with fitness score: none, duration 7.374345ms
invalid solution with fitness score: none, duration 7.667144ms
invalid solution with fitness score: none, duration 7.323526ms
invalid solution with fitness score: none, duration 7.250843ms
invalid solution with fitness score: none, duration 7.503847ms
invalid solution with fitness score: none, duration 7.300115ms
invalid solution with fitness score: none, duration 7.27096ms
invalid solution with fitness score: none, duration 7.400665ms
x1: 6.49999, x2: 7 = 58.99992 (fitness score:     8, duration 10.502185ms)
x1: 6.49996, x2: 7 = 58.99965 (fitness score:    35, duration 12.44276ms)
```

**Comment by basvanwesting** [comment]
I did some changes to solve the hill-climb local optimum issue:
* HillClimb now always uses a neighbouring mutation, as is expected for a hill-climbing algorithm
* HillClimb now has a random_chromosome_probability, which can be used to get out of a local optimum

Run with `cargo run --example hill_climb_milp --release`

The results are much better:

```
x1: 6.50000, x2: 7 = 58.99999 (fitness score:     0, duration 12.473057ms)
x1: 6.87500, x2: 4 = 58.99999 (fitness score:     0, duration 7.67362ms)
x1: 6.75002, x2: 5 = 59.00013 (fitness score:    13, duration 17.062094ms)
x1: 6.49992, x2: 7 = 58.99939 (fitness score:    61, duration 13.309105ms)
x1: 6.87498, x2: 4 = 58.99987 (fitness score:    12, duration 13.062268ms)
x1: 6.87500, x2: 4 = 58.99997 (fitness score:     3, duration 16.778876ms)
x1: 6.87497, x2: 4 = 58.99979 (fitness score:    21, duration 10.927678ms)
x1: 6.87501, x2: 4 = 59.00009 (fitness score:     8, duration 22.206118ms)
x1: 6.62500, x2: 6 = 59.00000 (fitness score:     0, duration 8.707532ms)
x1: 6.87500, x2: 4 = 59.00001 (fitness score:     1, duration 14.208433ms)
```

**Comment by basvanwesting** [comment]
If there is no known best value, the strategy just keeps on trying until it hits the max-stale-generations.
That is why the Fitness value is an isize, it needs te be able to become stale at some precision (defined in the fitness function, so the strategy doesn't have to know the precision to round).

Also I spiked a directed-hill-climb approach. In this approach all neigbours in all directions are tested. The results are very promising:

```
x1: 6.62500, x2: 6 = 59.00001 (fitness score:     0, duration 1.441595ms)
x1: 6.87500, x2: 4 = 59.00001 (fitness score:     0, duration 3.124381ms)
x1: 6.87500, x2: 4 = 59.00001 (fitness score:     0, duration 1.369349ms)
x1: 6.75000, x2: 5 = 59.00001 (fitness score:     0, duration 1.314995ms)
x1: 6.87500, x2: 4 = 59.00000 (fitness score:     0, duration 1.268921ms)
x1: 6.75000, x2: 5 = 59.00000 (fitness score:     0, duration 1.543982ms)
x1: 6.87500, x2: 4 = 59.00001 (fitness score:     0, duration 1.467648ms)
x1: 6.75000, x2: 5 = 59.00001 (fitness score:     0, duration 1.261714ms)
x1: 6.62500, x2: 6 = 59.00000 (fitness score:     0, duration 3.615059ms)
x1: 6.87500, x2: 4 = 59.00001 (fitness score:     0, duration 1.739247ms)
``` 

I need to cleanup etc. before this is pushed.

**Comment by SimonG85** [comment]
I tried your example on Matlab and it takes 0.0261 seconds to be evaluated.

**Comment by basvanwesting** [comment]
OK, I pushed a quick steepest ascent hill climbing approach. It is end-of-day for me, I'll clean up and refactor a bit later.
See the `hill_climb_milp` example:

```
    let hill_climb_builder = HillClimb::builder()
        .with_genotype(genotype)
        .with_variant(HillClimbVariant::Steepest)
        .with_max_stale_generations(100000)
        .with_target_fitness_score(0)
        .with_random_chromosome_probability(0.2)
        .with_fitness_ordering(FitnessOrdering::Minimize)
        .with_fitness(MILPFitness);
```

Results are very nice:

```
x1: 6.87500, x2: 4 = 59.00000 (fitness score:     0, duration 2.968865ms)
x1: 6.87500, x2: 4 = 59.00000 (fitness score:     0, duration 2.240059ms)
x1: 6.87500, x2: 4 = 59.00000 (fitness score:     0, duration 2.187021ms)
x1: 6.87500, x2: 4 = 59.00001 (fitness score:     0, duration 1.984028ms)
x1: 6.75000, x2: 5 = 59.00000 (fitness score:     0, duration 2.47021ms)
x1: 6.87500, x2: 4 = 59.00000 (fitness score:     0, duration 2.889892ms)
x1: 6.87500, x2: 4 = 59.00000 (fitness score:     0, duration 2.653452ms)
x1: 6.87500, x2: 4 = 59.00000 (fitness score:     0, duration 2.98283ms)
x1: 6.87500, x2: 4 = 59.00001 (fitness score:     0, duration 3.502453ms)
x1: 6.75000, x2: 5 = 59.00001 (fitness score:     0, duration 4.371491ms)
```

**Comment by SimonG85** [comment]
That's great! Thanks

**Comment by basvanwesting** [comment]
I discovered an issue in the MILP example: the constraints were not set correctly (some minus signs were missing).

BEFORE:
`if x1 + 2.0 * x2 >= 14.0 && -4.0 * x1 - x2 <= 33.0 && 2.0 * x1 + x2 <= 20.0 { ... }`

AFTER:
`if x1 + 2.0 * x2 >= -14.0 && -4.0 * x1 - x2 <= -33.0 && 2.0 * x1 + x2 <= 20.0 { ... }`

But when fixing the constraints, the solution can no longer find the 59.0 optimum, and finds 60.0 instead.
I think the optimal solution lies on a difficult to reach path by the hill-climbing strategy, where the erroneous constraints created an alternative path to reach it.

So the algorithm now produces the following:

```
x1: 6.75003, x2: 6 => 60.00022 (best_iteration: 882, best_generation:   105, duration: 4.878767ms)
x1: 6.75000, x2: 6 => 60.00001 (best_iteration: 600, best_generation:   174, duration: 4.396044ms)
x1: 6.75011, x2: 6 => 60.00090 (best_iteration: 638, best_generation:    78, duration: 3.719765ms)
x1: 6.75001, x2: 6 => 60.00006 (best_iteration: 787, best_generation:   136, duration: 3.260046ms)
x1: 6.75011, x2: 6 => 60.00089 (best_iteration: 147, best_generation:    91, duration: 3.324747ms)
x1: 6.75010, x2: 6 => 60.00082 (best_iteration: 138, best_generation:   103, duration: 3.903767ms)
x1: 6.75000, x2: 6 => 60.00002 (best_iteration: 230, best_generation:    95, duration: 3.315963ms)
x1: 6.75001, x2: 6 => 60.00005 (best_iteration: 152, best_generation:   261, duration: 3.491926ms)
x1: 6.75000, x2: 6 => 60.00001 (best_iteration: 584, best_generation:   134, duration: 3.50139ms)
x1: 6.75001, x2: 6 => 60.00008 (best_iteration: 809, best_generation:   158, duration: 3.184671ms)
```

**Comment by basvanwesting** [comment]
Some additional changes:
* Add IncrementalGenotype trait, now required by the HillClimb strategy. The neighbour concept is implemented here.
* Add scaling to the neighbouring mutations, this was you can reduce the step size and zoom in on the optimal solution.
* A minumum scaling factor is now added as terminating condition for the HillClimb strategy.

**Comment by SimonG85** [comment]
With ceil instead of floor the x_2 is right while the fitness isn't.

**Comment by SimonG85** [comment]
Of course the specific intlinprog should be more specific than GA (Range-Kutta and its friends :D)

**Comment by basvanwesting** [comment]
Indeed. I'm closing this issue now. I don't think we have any remaining questions regarding this topic.
